CountryCity/Controllers/PagesController.cs
using CountryCity.Context;
using CountryCity.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace CountryCity.Controllers
{
    [Authorize()]
    public class PagesController : Controller
    {

        IMemoryCache _memoryCache;

        CountryContext _countryContext;

        public PagesController(IMemoryCache memoryCache,CountryContext countryContext)
        {
            this._memoryCache = memoryCache;

            this._countryContext = countryContext;

           
        }

        public void Set()
        {
            var CountryList = _countryContext.Countries.ToList();

            _memoryCache.Set("Countries", CountryList,new MemoryCacheEntryOptions
            {
                AbsoluteExpiration = DateTime.Now.AddSeconds(30), //Cache'deki datanın ömrü

                SlidingExpiration = TimeSpan.FromSeconds(10), //10 sn içerisinde istek yapılırsa cache'de kalma süresi 10 sn daha artacaktır.
                Priority = CacheItemPriority.Normal
            });; //(key, Veriler,, Ayarlamalar)
           
        }

        



        [Authorize(Roles = "Administrator")]
        public IActionResult Page1()
        {                      

            if (_memoryCache.TryGetValue<List<Country>>("Countries",out List<Country> value))
            {
                var C = _memoryCache.Get<List<Country>>("Countries");

                return View(C);
            }          


            return View();
        }

        [Authorize(Roles = "Editor")]
        public IActionResult Page2()
        {

            
            return View();
        }

        [Authorize(Roles = "Moderator")]
        public IActionResult Page3()
        {
            
            return View();
        }

        [Authorize(Roles="Administrator")]
        public IActionResult CacheTetikle()
        {
            Set();
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult ResetCache()
        {
            _memoryCache.Remove("Countries");
            return View();

        }

        
    }
}

CountryCity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CountryCity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CountryCity.styles.css" asp-append-version="true" />

	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

	<script src="~/lib/jquery-validate/additional-methods.js"></script>
	<script src="~/lib/jquery-validate/additional-methods.min.js"></script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CountryCity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Home/Index">Home</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>*@
                      @*  <a asp-action="Page1" asp-controller="Pages">Page 1</a> |
                        <a asp-action="Page2" asp-controller="Pages">Page 2</a> |
                        <a asp-action="Page3" asp-controller="Pages">Page 3</a> |*@
                       
                        <br />

                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Role/Index">Roles</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Role/CreateRole">CreateRole</a>
                        </li>

                        <li class="nav-item">
                           <a class="nav-link text-dark" href="/Home/Logout">LogOut</a>
                        </li>
                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CountryCity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @*&copy; 2022 - CountryCity - <a asp-area="" asp-page="/Privacy">Privacy</a>*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Pages/Page1">Page1</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Pages/Page2">Page2</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Pages/Page3">Page3</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Pages/CacheTetikle" class="btn btn-outline-warning">In-Memory Cache Set</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Pages/ResetCache" class="btn btn-outline-warning">In-Memory Cache Remove</a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>


        
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>